name: Create a comment on new issue

on:
  issues:
    types: [opened]

jobs:
  content-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "Dump GitHub context"
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          echo '${{ toJSON(github.event) }}' | jq
        shell: bash
